# Generated by Django 4.0 on 2021-12-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название игры')),
                ('cash_limit', models.CharField(default='0', max_length=25, verbose_name='Бюджет')),
                ('stop_registration_date', models.DateTimeField(verbose_name='Окончание регистрации')),
                ('sending_gift_date', models.DateField(verbose_name='Дата отправки подарков')),
                ('is_finish', models.BooleanField(db_index=True, default=False, verbose_name='Игра закончена')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, verbose_name='Фамилия')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='Chat id')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('mail', models.CharField(blank=True, max_length=250, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='PlayersInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='bot.game', verbose_name='Номер игры')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='bot.player', verbose_name='Участник')),
                ('santa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='santa', to='bot.player', verbose_name='Тайный Санта')),
            ],
            options={
                'verbose_name': 'Игрок в игре',
                'verbose_name_plural': 'Игроки в игре',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='bot.player', verbose_name='Владелец игры'),
        ),
    ]
