# Generated by Django 4.0 on 2021-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_game_sending_gift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stop_registration_date',
            field=models.TextField(verbose_name='Окончание регистрации'),
        ),
    ]
